import type { AppLanguage } from './models';

export const STRINGS = {
  en: {
    appName: 'anote',
    allNotes: 'All Notes',
    starred: 'Starred',
    recycleBin: 'Recycle Bin',
    folders: 'Folders',
    notes: 'Notes',
    settings: 'Settings',
    newNote: 'New Note',
    newFolder: 'New Folder',
    renameFolder: 'Rename',
    deleteFolder: 'Delete',
    searchPlaceholder: 'Search notes...',
    noNotesTitle: 'No notes yet',
    noNotesSubtitle: 'Create a note and start writing.',
    noSearchTitle: 'No matching notes',
    noSearchSubtitle: 'Try another keyword.',
    restore: 'Restore',
    moveToTrash: 'Move to Bin',
    deleteForever: 'Delete Forever',
    pin: 'Pin',
    unpin: 'Unpin',
    star: 'Star',
    unstar: 'Unstar',
    addToFolder: 'Add to Folders',
    syncNow: 'Sync Now',
    syncIdle: 'Ready to sync',
    syncSuccess: 'Sync finished.',
    syncErrorPrefix: 'Sync failed:',
    previewMode: 'Editor',
    codeMode: 'HTML',
    createFirstNote: 'Create your first note',
    saveSettings: 'Save',
    desktopSettings: 'Desktop settings',
    desktopSettingsTitle: 'Bring the desktop app up to speed',
    basics: 'Basics',
    language: 'Language',
    font: 'Font',
    syncProvider: 'Sync provider',
    currentVersion: 'Current version',
    latestRelease: 'Latest release',
    checkUpdate: 'Check Update',
    updateAvailable: 'Update available',
    upToDate: 'Up to date',
    updateCheckFailed: 'Update check failed',
    downloadLatest: 'Download Latest',
    saveGithubConfig: 'Save GitHub config',
    saveWebdavConfig: 'Save WebDAV config',
    clearConfig: 'Clear config',
    repoLabel: 'Repo',
    tokenLabel: 'Token',
    branchLabel: 'Branch',
    serverUrl: 'Server URL',
    username: 'Username',
    password: 'Password / App Password',
    remoteFile: 'Remote file',
    saveSuccess: 'Saved.',
    configCleared: 'Configuration cleared.',
    missingGithubFields: 'Repo and token are required.',
    missingWebdavFields: 'Server URL, username, and password are required.',
    downloadFont: 'Download font',
    fontDownloaded: 'Font downloaded.',
    fontUnavailable: 'Download the font before using it.',
    fontDownloading: 'Downloading...',
    share: 'Share',
    copyText: 'Copy Text',
    copied: 'Copied.',
    uploadImage: 'Image',
    delete: 'Delete',
    wordUnit: 'words',
    light: 'Light',
    dark: 'Dark',
    longImage: 'Long Image',
    exportPng: 'Export PNG',
    exporting: 'Exporting...',
    close: 'Close',
  },
  zh: {
    appName: 'anote',
    allNotes: '全部',
    starred: '收藏',
    recycleBin: '回收站',
    folders: '文件夹',
    notes: '笔记',
    settings: '设置',
    newNote: '新建笔记',
    newFolder: '新建文件夹',
    renameFolder: '重命名',
    deleteFolder: '删除',
    searchPlaceholder: '搜索便签...',
    noNotesTitle: '还没有笔记',
    noNotesSubtitle: '新建一条笔记开始写吧。',
    noSearchTitle: '没有匹配结果',
    noSearchSubtitle: '换个关键词试试。',
    restore: '恢复',
    moveToTrash: '移到回收站',
    deleteForever: '永久删除',
    pin: '置顶',
    unpin: '取消置顶',
    star: '收藏',
    unstar: '取消收藏',
    addToFolder: '添加到文件夹',
    syncNow: '立即同步',
    syncIdle: '准备同步',
    syncSuccess: '同步完成。',
    syncErrorPrefix: '同步失败：',
    previewMode: '编辑',
    codeMode: 'HTML',
    createFirstNote: '新建第一条笔记',
    saveSettings: '保存',
    desktopSettings: '桌面设置',
    desktopSettingsTitle: '把桌面端做成真正可用的软件',
    basics: '基础设置',
    language: '语言',
    font: '字体',
    syncProvider: '同步方式',
    currentVersion: '当前版本',
    latestRelease: '最新发布',
    checkUpdate: '检查更新',
    updateAvailable: '有新版本可用',
    upToDate: '已经是最新版本',
    updateCheckFailed: '检查更新失败',
    downloadLatest: '下载最新版本',
    saveGithubConfig: '保存 GitHub 配置',
    saveWebdavConfig: '保存 WebDAV 配置',
    clearConfig: '清空配置',
    repoLabel: '仓库',
    tokenLabel: 'Token',
    branchLabel: '分支',
    serverUrl: '服务器地址',
    username: '用户名',
    password: '密码 / 应用密码',
    remoteFile: '远程文件',
    saveSuccess: '已保存。',
    configCleared: '配置已清空。',
    missingGithubFields: '仓库和 Token 不能为空。',
    missingWebdavFields: '服务器地址、用户名和密码不能为空。',
    downloadFont: '下载字体',
    fontDownloaded: '字体已下载。',
    fontUnavailable: '请先下载字体再使用。',
    fontDownloading: '下载中...',
    share: '分享',
    copyText: '复制文字',
    copied: '已复制。',
    uploadImage: '图片',
    delete: '删除',
    wordUnit: '字',
    light: '浅色',
    dark: '深色',
    longImage: '长图',
    exportPng: '导出 PNG',
    exporting: '导出中...',
    close: '关闭',
  },
} as const;

export function getString(language: AppLanguage, key: keyof (typeof STRINGS)['en']): string {
  return STRINGS[language][key];
}
